version: '3.1'
services:
  

  credit-user-db:
    image: 'postgres'
    container_name: 'socks-db-container' 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
    ports:
      - 1001:5432