version: '3.1'
services:
  credit-user-service:
    image: 'nikitkamzgb/socks-backspark-iso'
    container_name: 'socks-service-container'
    depends_on:
      - socks-db
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://socks-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwe
    ports:
      - 8889:8888

  socks-db:
    image: 'postgres'
    container_name: 'socks-db-container' 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
    ports:
      - 1001:5432